### ISSUE TITLE
timescale param

### ISSUE THREAD

**Issue by limogin** [bernorieder/lineminer#1]
It is possible that the script need to obtain the timescale param from the $_POST var? In this case, I think that the best option to obtain the value will be some as this:

```
// $timescale = ($_GET["timescale"] == "") ? $_GET["timescale"]:"week";
if (isset($_POST['timescale'])) {
	$timescale = $_POST['timescale'];
} else if (isset($_GET['timescale'])) {
	$timescale = $_GET['timescale'];
} else {
    $timescale = 'week';
};

```

Thanks in advance

**Comment by bernorieder** [comment]
Hi, yes, there was a bug with the timescale, fixed it now.
Thanks!
